spring:

  application:
    name: timesheet

  data:
    mongodb:
    #uri: mongodb+srv://localhost/?readPreference=primary&ssl=false
    host: localhost
    port: 27017
    #username: testuser2
    #password: test
    #database: timesheet

  server:
    port: 9090
    servlet:
      context-path: /timesheet